version: '3.8'

services:
  web:
    build: ./app
    container_name: flask-api
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app-net

  db:
    image: postgres:14
    container_name: pg-db
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    networks:
      - app-net

volumes:
  db_data:

networks:
  app-net:
